let sentences = [
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Through a crucible for the ages America has been tested anew and America has risen to the challenge.',
  'Today, we celebrate the triumph not of a candidate, but of a cause, the cause of democracy.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'The will of the people has been heard and the will of the people has been heeded.',
  'We have learned again that democracy is precious.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
  'Democracy is fragile.',
  'And at this hour, my friends, democracy has prevailed.',
  'So now, on this hallowed ground where just days ago violence sought to shake this Capitol’s very foundation, we come together as one nation, under God, indivisible, to carry out the peaceful transfer of power as we have for more than two centuries.',
  'We look ahead in our uniquely American way – restless, bold, optimistic – and set our sights on the nation we know we can be and we must be.',
  'I thank my predecessors of both parties for their presence here.',
  'I thank them from the bottom of my heart.',
];

module.exports = sentences;