const nNo = Number("")
const nZero = Number(0)
const nNegZero = Number(-0)
const nOhNine = Number(009)
const nDec = Number(3.14)
const nZdot = Number(0.)
const nDot = Number(".")
const nTh = Number(0xaf)
const nThStr = Number("0xaf")
console.log({nNo})
console.log({nZero})
console.log({nNegZero})
console.log({nOhNine})
console.log({nDec})
console.log({nZdot})
console.log({nDot})
console.log({nTh})
console.log({nThStr})