const strNull = String(null)
const strUndef = String(undefined)
const strTrue = String(true)
const strFalse = String(false)
const strDec = String(3.14159265)
const strZero = String(0)
const strNegZero = String(-0)
console.log({strNull})
console.log({strUndef})
console.log({strTrue})
console.log({strFalse})
console.log({strDec})
console.log({strZero})
console.log({strNegZero})