const strNull = String(null)
const strUndef = String(undefined)
const strTrue = String(true)
const strFalse = String(false)
const strDec = String(3.14159265)
const strZero = String(0)
const strNegZero = String(-0)
const strArr = String([])
const strArrNums = String([1,2,3])
const strArrOdds = String([null,undefined])
const strArrArrs = String([[],[],[]])
const strArrEmpty = String([,,,])
const strObj = String({})
const strObjA = String({a:2})
console.log({strNull})
console.log({strUndef})
console.log({strTrue})
console.log({strFalse})
console.log({strDec})
console.log({strZero})
console.log({strNegZero})
console.log({strArr})
console.log({strArrNums})
console.log({strArrOdds})
console.log({strArrArrs})
console.log({strArrEmpty})
console.log({strObj})
console.log({strObjA})